#ifndef PROCESSFLOWPLUGIN_PROCESSFLOWUISTYLE_H
#define PROCESSFLOWPLUGIN_PROCESSFLOWUISTYLE_H

/// @file ProcessFlowUiStyle.h
/// @brief 工艺流程侧栏统一视觉（工业灰蓝，避免系统默认灰窗）

#include <QString>

inline QString processFlowSideChromeStyle()
{
	return QStringLiteral(
		"QWidget#ProcessFlowSideRoot {"
		"  background-color: #EEF1F4;"
		"}"
		"QFrame#ProcessFlowCard {"
		"  background-color: #FFFFFF;"
		"  border: 1px solid #D5DCE3;"
		"  border-radius: 10px;"
		"}"
		"QLabel#ProcessFlowSectionTitle {"
		"  color: #1A2332;"
		"  font-weight: 700;"
		"  font-size: 13px;"
		"}"
		"QLabel#ProcessFlowHint {"
		"  color: #6B7785;"
		"  font-size: 11px;"
		"}"
		"QLabel#ProcessFlowFieldLabel {"
		"  color: #4A5562;"
		"  font-size: 12px;"
		"}"
		"QListWidget#ProcessFlowNodeList {"
		"  background: transparent;"
		"  border: none;"
		"  outline: none;"
		"  padding: 4px;"
		"}"
		"QListWidget#ProcessFlowNodeList::item {"
		"  color: #1F2933;"
		"  padding: 8px 10px;"
		"  margin: 2px 2px;"
		"  border-radius: 8px;"
		"  min-height: 22px;"
		"}"
		"QListWidget#ProcessFlowNodeList::item:hover {"
		"  background-color: #F3F6F9;"
		"}"
		"QListWidget#ProcessFlowNodeList::item:selected {"
		"  background-color: #E4EEF8;"
		"  color: #163A5F;"
		"}"
		"QComboBox, QDoubleSpinBox, QSpinBox, QLineEdit {"
		"  background-color: #FFFFFF;"
		"  border: 1px solid #C9D3DD;"
		"  border-radius: 6px;"
		"  padding: 4px 8px;"
		"  min-height: 24px;"
		"  color: #1F2933;"
		"  selection-background-color: #2E7DD1;"
		"}"
		"QComboBox:hover, QDoubleSpinBox:hover, QLineEdit:hover {"
		"  border-color: #9EB2C5;"
		"}"
		"QComboBox:focus, QDoubleSpinBox:focus, QLineEdit:focus {"
		"  border-color: #2E7DD1;"
		"}"
		"QComboBox:disabled, QDoubleSpinBox:disabled {"
		"  background-color: #F1F4F7;"
		"  color: #8A94A0;"
		"}"
		"QComboBox::drop-down {"
		"  border: none;"
		"  width: 22px;"
		"}"
		"QPushButton {"
		"  background-color: #FFFFFF;"
		"  border: 1px solid #C9D3DD;"
		"  border-radius: 6px;"
		"  padding: 5px 10px;"
		"  color: #1F2933;"
		"  min-height: 24px;"
		"}"
		"QPushButton:hover {"
		"  background-color: #F5F8FB;"
		"  border-color: #9EB2C5;"
		"}"
		"QPushButton:pressed {"
		"  background-color: #E8EEF4;"
		"}"
		"QPushButton:disabled {"
		"  color: #9AA3AD;"
		"  background-color: #F3F5F7;"
		"}"
		"QPushButton#ProcessFlowPrimaryButton {"
		"  background-color: #2E7DD1;"
		"  border: 1px solid #256BB5;"
		"  color: #FFFFFF;"
		"}"
		"QPushButton#ProcessFlowPrimaryButton:hover {"
		"  background-color: #3A8AE0;"
		"}"
		"QPushButton#ProcessFlowPrimaryButton:pressed {"
		"  background-color: #256BB5;"
		"}"
		"QPushButton#ProcessFlowPrimaryButton:disabled {"
		"  background-color: #A9C5E3;"
		"  border-color: #A9C5E3;"
		"  color: #F5F9FC;"
		"}"
		"QTableWidget {"
		"  background-color: #FFFFFF;"
		"  border: 1px solid #D5DCE3;"
		"  border-radius: 8px;"
		"  gridline-color: #E8EEF3;"
		"  selection-background-color: #E4EEF8;"
		"  selection-color: #163A5F;"
		"}"
		"QHeaderView::section {"
		"  background-color: #F5F8FB;"
		"  color: #4A5562;"
		"  border: none;"
		"  border-bottom: 1px solid #D5DCE3;"
		"  border-right: 1px solid #E8EEF3;"
		"  padding: 5px 8px;"
		"  font-weight: 600;"
		"}"
		"QSplitter::handle:vertical {"
		"  background: #EEF1F4;"
		"  height: 8px;"
		"}"
		"QSplitter::handle:vertical:hover {"
		"  background: #D5DCE3;"
		"}");
}

#endif
