#ifndef CLOUDSIMPLUGINHOST_PLUGIN_HOST_GLOBAL_H
#define CLOUDSIMPLUGINHOST_PLUGIN_HOST_GLOBAL_H

/// @file plugin_host_global.h
/// @brief CloudSimPluginHost 导出宏

#define PLUGIN_HOST_STATIC

#endif // CLOUDSIMPLUGINHOST_PLUGIN_HOST_GLOBAL_H
