#ifndef CLOUDSIMWEBGATEWAY_CLOUDSIM_WEB_GATEWAY_GLOBAL_H
#define CLOUDSIMWEBGATEWAY_CLOUDSIM_WEB_GATEWAY_GLOBAL_H

/// @file cloudsim_web_gateway_global.h
/// @brief CloudSimWebGateway 导出宏（静态库为空）

#define CLOUDSIM_WEB_GATEWAY_API

#endif // CLOUDSIMWEBGATEWAY_CLOUDSIM_WEB_GATEWAY_GLOBAL_H
